<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="<?= base_url('resources/css/blog/styles.css') ?>" rel="stylesheet" />
        <style>
            @keyframes ldio-jsxn2qe688r
            {
                0% { opacity: 1 }
                100% { opacity: 0 }
            }

            .ldio-jsxn2qe688r div
            {
                left: 94px;
                top: 48px;
                position: absolute;
                animation: ldio-jsxn2qe688r linear 1s infinite;
                background: #ffde59;
                width: 12px;
                height: 24px;
                border-radius: 6px / 12px;
                transform-origin: 6px 52px;
            }

            .ldio-jsxn2qe688r div:nth-child(1)
            {
                transform: rotate(0deg);
                animation-delay: -0.9166666666666666s;
                background: #ffde59;
            }

            .ldio-jsxn2qe688r div:nth-child(2)
            {
                transform: rotate(30deg);
                animation-delay: -0.8333333333333334s;
                background: #ffde59;
            }

            .ldio-jsxn2qe688r div:nth-child(3)
            {
                transform: rotate(60deg);
                animation-delay: -0.75s;
                background: #ffde59;
            }

            .ldio-jsxn2qe688r div:nth-child(4)
            {
                transform: rotate(90deg);
                animation-delay: -0.6666666666666666s;
                background: #ffde59;
            }

            .ldio-jsxn2qe688r div:nth-child(5)
            {
                transform: rotate(120deg);
                animation-delay: -0.5833333333333334s;
                background: #ffde59;
            }

            .ldio-jsxn2qe688r div:nth-child(6)
            {
                transform: rotate(150deg);
                animation-delay: -0.5s;
                background: #ffde59;
            }

            .ldio-jsxn2qe688r div:nth-child(7)
            {
                transform: rotate(180deg);
                animation-delay: -0.4166666666666667s;
                background: #ffde59;
            }

            .ldio-jsxn2qe688r div:nth-child(8)
            {
                transform: rotate(210deg);
                animation-delay: -0.3333333333333333s;
                background: #ffde59;
            }

            .ldio-jsxn2qe688r div:nth-child(9)
            {
                transform: rotate(240deg);
                animation-delay: -0.25s;
                background: #ffde59;
            }

            .ldio-jsxn2qe688r div:nth-child(10)
            {
                transform: rotate(270deg);
                animation-delay: -0.16666666666666666s;
                background: #ffde59;
            }

            .ldio-jsxn2qe688r div:nth-child(11)
            {
                transform: rotate(300deg);
                animation-delay: -0.08333333333333333s;
                background: #ffde59;
            }

            .ldio-jsxn2qe688r div:nth-child(12)
            {
                transform: rotate(330deg);
                animation-delay: 0s;
                background: #ffde59;
            }

            .loadingio-spinner-spinner-65dox1ras4p
            {
                width: 200px;
                height: 200px;
                display: inline-block;
                overflow: hidden;
                background: none;
            }

            .ldio-jsxn2qe688r
            {
                width: 100%;
                height: 100%;
                position: relative;
                transform: translateZ(0) scale(1);
                backface-visibility: hidden;
                transform-origin: 0 0; /* see note above */
            }

            .ldio-jsxn2qe688r div { box-sizing: content-box; }
            /* generated by https://loading.io/ */
            /* More info https://loading.io/asset/389885 */

            .loader
            {
                height: 100vh;
                display: flex;
                justify-content: center;
                align-items: center;
            }

            .hidden
            {
                overflow: hidden;
            }
        </style>
    </head>
    <body>
        <div class="loader">
            <div class="loadingio-spinner-spinner-65dox1ras4p">
                <div class="ldio-jsxn2qe688r">
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                <div></div>
                </div>
            </div>
        </div>

        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="<?= base_url() ?>">Find my assets</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="<?= base_url() ?>">Ir a inicio</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page Header-->
        <header class="masthead" id="header-img">
            <div class="container position-relative px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <div class="post-heading">
                            <h1 id="blog-title"></h1>
                            <span class="meta">
                                Publicado el dia -- de ------- de 202-
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Post Content-->
        <article class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7" id="content">
                        
                    </div>
                </div>
            </div>
        </article>
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Find my Assets 2021</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="<?= base_url('resources/js/blog/scripts.js') ?>"></script>
        <!-- jQuery library -->
        <script src="<?= base_url('resources/plugins/jquery/jquery-3.5.1.min.js') ?>"></script>
        <script>
            $.ajax({
                //url: 'https://admin.findmy-asstes.com/api/blogs',
                url: 'http://localhost:8000/api/blogs/<?= $id ?>',
                type: 'GET',
                dataType: 'json',
            })
            .done(response =>
            {
                $('#content').html(response.content);
                $('#blog-title').html(response.title);
                $('#header-img').css('background-image', `url('${response.image}')`);

                $('.loader').fadeOut( 'slow' );
                $('body').removeClass( 'hidden' );
            });
        </script>
    </body>
</html>
